# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


ActiveRecord::Base.transaction do
  User.destroy_all
  Post.destroy_all
  Follow.destroy_all
  Like.destroy_all
  Comment.destroy_all


  u1= User.create!({username: 'instagram', password: 'starwars', bio: "Capture and share the world's moments",
    avatar: 'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_prof.jpg'})
  u6 = User.create!({username: 'blackbeard', password: 'starwars', bio: 'Bottles of rum',
    avatar: 'https://s3.amazonaws.com/ragtagio-dev/blackbeard/blackbeard_prof.jpeg'})
  u7 = User.create!({username: 'animals', password: 'starwars', bio: 'Hakuna Matata',
    avatar: 'https://s3.amazonaws.com/ragtagio-dev/animals/animals_prof.jpg'})
  u2 = User.create!({username: 'gordon', password: 'starwars', bio: "It's raw!",
    avatar: 'https://s3.amazonaws.com/ragtagio-dev/gordon/gordon_prof.jpeg'})
  User.create!({username: 'sportsball', password: 'starwars'})
  User.create!({username: 'pocketrockets', password: 'starwars'})
  u8 = User.create!({username: 'mamba', password: 'starwars'})
  User.create!({username: 'salsa', password: 'starwars'})
  User.create!({username: 'ragbaby', password: 'starwars'})
  u3 = User.create!({username: 'ragtag', password: 'starwars', bio: "The world is your closet",
    avatar: 'https://s3.amazonaws.com/ragtagio-dev/ragtag/demo_prof.jpeg'})
  User.create!({username: 'maroon55', password: 'starwars'})
  User.create!({username: 'navyJ', password: 'starwars'})
  User.create!({username: 'fauxhawk', password: 'starwars'})
  User.create!({username: 'milkshakes', password: 'starwars'})
  User.create!({username: 'washing_machine', password: 'starwars'})
  u4 = User.create!({username: 'bananaR', password: 'starwars', bio:"a banana a day",
    avatar: 'https://s3.amazonaws.com/ragtagio-dev/bananaR/bananaR_prof.jpeg'})
  User.create!({username: 'j_krew', password: 'starwars'})
  User.create!({username: 'm_and_h', password: 'starwars'})
  u9 = User.create!({username: 'kalvinClein', password: 'starwars'})
  User.create!({username: 'VonatellaD', password: 'starwars'})
  User.create!({username: 'sarudeDandstorm', password: 'starwars'})
  User.create!({username: 'givenChi', password: 'starwars'})
  User.create!({username: 'polo_assassin', password: 'starwars'})
  User.create!({username: 'u_nick_lo', password: 'starwars'})
  User.create!({username: 'apparel_america', password: 'starwars'})
  User.create!({username: 'brock_brothers', password: 'starwars'})
  User.create!({username: 'hill_figure', password: 'starwars'})
  u5 = User.create!({username: 'yeezies', password: 'starwars', bio: "If you fall on concrete, that's yo asphalt",
    avatar: 'https://s3.amazonaws.com/ragtagio-dev/yeezies/yeezies_prof.jpeg'})
  User.create!({username: 'forever23', password: 'starwars'})
  User.create!({username: 'AnnsTailor', password: 'starwars'})

  Follow.create!({follower_id: u3.id, followee_id: u1.id})
  Follow.create!({follower_id: u3.id, followee_id: u2.id})
  Follow.create!({follower_id: u3.id, followee_id: u4.id})
  Follow.create!({follower_id: u3.id, followee_id: u5.id})
  Follow.create!({follower_id: u3.id, followee_id: u7.id})
  Follow.create!({follower_id: u5.id, followee_id: u3.id})
  Follow.create!({follower_id: u5.id, followee_id: u7.id})
  Follow.create!({follower_id: u5.id, followee_id: u1.id})
  Follow.create!({follower_id: u2.id, followee_id: u3.id})
  Follow.create!({follower_id: u2.id, followee_id: u5.id})
  Follow.create!({follower_id: u2.id, followee_id: u1.id})
  Follow.create!({follower_id: u1.id, followee_id: u7.id})
  Follow.create!({follower_id: u1.id, followee_id: u9.id})
  Follow.create!({follower_id: u1.id, followee_id: u3.id})
  Follow.create!({follower_id: u1.id, followee_id: u4.id})

  p23 = Post.create!({user_id:u3.id, image: 'https://s3.amazonaws.com/ragtagio-dev/ragtag/demo_5.jpeg'})
  p3 = Post.create!({user_id:u1.id, body:'views #nofilter', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_3.jpeg'})
  p4 = Post.create!({user_id:u1.id, body:'joy junkies', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_4.jpeg'})
  p60 = Post.create!({user_id: u6.id, body:'night streets', image:'https://s3.amazonaws.com/ragtagio-dev/blackbeard/blackbeard_1.jpeg'})
  p13 = Post.create!({user_id:u2.id, body:'slice of #heaven', image: 'https://s3.amazonaws.com/ragtagio-dev/gordon/gordon_3.jpeg'})
  p5 = Post.create!({user_id:u1.id, body:'always exploring #nature', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_5.jpeg'})
  p6 = Post.create!({user_id:u1.id, body:'salmon or pink?', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_6.jpeg'})
  p2 = Post.create!({user_id:u1.id, body:'a very good boy', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_2.jpeg'})
  p8 = Post.create!({user_id:u1.id, body:"sparks", image: 'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_8.jpeg'})
  p9 = Post.create!({user_id:u1.id, body:'freckles?', image: 'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_9.jpeg'})
  p10 = Post.create!({user_id:u1.id, body:'on the grind #coffee', image: 'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_10.jpeg'})
  p11 = Post.create!({user_id:u2.id, body:'in the kitchen wrist twisting', image: 'https://s3.amazonaws.com/ragtagio-dev/gordon/gordon_1.jpg'})
  p53 = Post.create!({user_id: u1.id, body:'nectarines', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_18.jpeg'})
  p12 = Post.create!({user_id:u2.id, body:'eating the food my food eats', image: 'https://s3.amazonaws.com/ragtagio-dev/gordon/gordon_2.jpg'})
  p14 = Post.create!({user_id:u2.id, body:"don't stew over this", image: 'https://s3.amazonaws.com/ragtagio-dev/gordon/gordon_4.jpeg'})
  p15 = Post.create!({user_id:u2.id, body:"real smooth", image: 'https://s3.amazonaws.com/ragtagio-dev/gordon/gordon_5.jpeg'})
  p59 = Post.create!({user_id: u6.id, body:'nonchalant afternoon', image:'https://s3.amazonaws.com/ragtagio-dev/blackbeard/blackbeard_2.jpeg'})
  p49 = Post.create!({user_id: u1.id, body:'#squad', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_14.jpeg'})
  p40 = Post.create!({user_id:u5.id, body:"Wearing these next week", image: 'https://s3.amazonaws.com/ragtagio-dev/yeezies/yeezies_8.jpeg'})
  p17 = Post.create!({user_id:u2.id, body:'caramelized goodness', image: 'https://s3.amazonaws.com/ragtagio-dev/gordon/gordon_7.jpeg'})
  p29 = Post.create!({user_id:u4.id, body:'slice bananas',image: 'https://s3.amazonaws.com/ragtagio-dev/bananaR/bananaR_3.jpeg'})
  p18 = Post.create!({user_id:u2.id, body:'winner winner wonton soup', image: 'https://s3.amazonaws.com/ragtagio-dev/gordon/gordon_8.jpeg'})
  p19 = Post.create!({user_id:u3.id, image: 'https://s3.amazonaws.com/ragtagio-dev/ragtag/demo_1.jpeg'})
  p20 = Post.create!({user_id:u3.id, image: 'https://s3.amazonaws.com/ragtagio-dev/ragtag/demo_2.jpeg'})
  p7 = Post.create!({user_id:u1.id, body:'stacked #foodie', image: 'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_7.jpeg'})
  p21 = Post.create!({user_id:u3.id, image: 'https://s3.amazonaws.com/ragtagio-dev/ragtag/demo_3.jpeg'})
  p24 = Post.create!({user_id:u3.id, image: 'https://s3.amazonaws.com/ragtagio-dev/ragtag/demo_6.jpeg'})
  p1 = Post.create!({user_id: u1.id, body:'#tbt', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_1.jpeg'})
  p25 = Post.create!({user_id:u3.id, body:'#twinning', image: 'https://s3.amazonaws.com/ragtagio-dev/ragtag/demo_7.jpg'})
  p26 = Post.create!({user_id:u3.id, image: 'https://s3.amazonaws.com/ragtagio-dev/ragtag/demo_8.jpeg'})
  p27 = Post.create!({user_id:u4.id, body:'go bananas', image: 'https://s3.amazonaws.com/ragtagio-dev/bananaR/bananaR_1.jpeg'})
  p54 = Post.create!({user_id: u1.id, body:'morning hike!', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_19.jpeg'})
  p28 = Post.create!({user_id:u4.id, body:'eat bananas',image: 'https://s3.amazonaws.com/ragtagio-dev/bananaR/bananaR_2.jpeg'})
  p57 = Post.create!({user_id: u6.id, body:'ornaments', image:'https://s3.amazonaws.com/ragtagio-dev/blackbeard/blackbeard_6.jpeg'})
  p58 = Post.create!({user_id: u6.id, body:'throwback', image:'https://s3.amazonaws.com/ragtagio-dev/blackbeard/blackbeard_3.jpeg'})
  p22 = Post.create!({user_id:u3.id, image: 'https://s3.amazonaws.com/ragtagio-dev/ragtag/demo_4.jpeg'})
  p30 = Post.create!({user_id:u4.id, body:'diced banana',image: 'https://s3.amazonaws.com/ragtagio-dev/bananaR/bananaR_4.jpeg'})
  p36 = Post.create!({user_id:u5.id, body:"Exam day sneakers", image: 'https://s3.amazonaws.com/ragtagio-dev/yeezies/yeezies_4.jpeg'})
  p31 = Post.create!({user_id:u4.id, body:'banana factory',image: 'https://s3.amazonaws.com/ragtagio-dev/bananaR/bananaR_5.jpeg'})
  p52 = Post.create!({user_id: u1.id, body:'ny or chicago pizza?', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_17.jpeg'})
  p32 = Post.create!({user_id:u4.id, body:'banana republic',image: 'https://s3.amazonaws.com/ragtagio-dev/bananaR/bananaR_6.jpeg'})
  p16 = Post.create!({user_id:u2.id, body:'fresh picked', image: 'https://s3.amazonaws.com/ragtagio-dev/gordon/gordon_6.jpeg'})
  p34 = Post.create!({user_id:u5.id, body:"For Aaliyah",image:'https://s3.amazonaws.com/ragtagio-dev/yeezies/yeezies_2.jpeg'})
  p37 = Post.create!({user_id:u5.id, body:'running from Egypt to South Africa', image: 'https://s3.amazonaws.com/ragtagio-dev/yeezies/yeezies_5.jpg'})
  p33 = Post.create!({user_id:u5.id, body:'windy city', image: 'https://s3.amazonaws.com/ragtagio-dev/yeezies/yeezies_1.jpg'})
  p56 = Post.create!({user_id: u6.id, body:'which one?', image:'https://s3.amazonaws.com/ragtagio-dev/blackbeard/blackbeard_4.jpeg'})
  p38 = Post.create!({user_id:u5.id, body:"What jacket would match this?", image: 'https://s3.amazonaws.com/ragtagio-dev/yeezies/yeezies_6.jpeg'})
  p39 = Post.create!({user_id:u5.id, body:"See in three dimensions", image: 'https://s3.amazonaws.com/ragtagio-dev/yeezies/yeezies_7.jpeg'})
  p41 = Post.create!({user_id:u7.id, image:'https://s3.amazonaws.com/ragtagio-dev/animals/animals_1.jpg'})
  p43 = Post.create!({user_id:u7.id, image:'https://s3.amazonaws.com/ragtagio-dev/animals/animals_2.jpeg'})
  p55 = Post.create!({user_id: u6.id, body:"the marketplace", image:'https://s3.amazonaws.com/ragtagio-dev/blackbeard/blackbeard_5.jpeg'})
  p45 = Post.create!({user_id:u7.id, image:'https://s3.amazonaws.com/ragtagio-dev/animals/animals_4.jpeg'})
  p46 = Post.create!({user_id: u1.id, body:'fall bliss', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_11.jpg'})
  p35 = Post.create!({user_id:u5.id, body:"Living spree",image: 'https://s3.amazonaws.com/ragtagio-dev/yeezies/yeezies_3.jpeg'})
  p47 = Post.create!({user_id: u1.id, body:'around the world', image: 'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_12.jpeg'})
  p48 = Post.create!({user_id: u1.id, body:'somewhere in the mountains', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_13.jpeg'})
  p50 = Post.create!({user_id: u1.id, body:'wonderland', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_15.jpeg'})
  p44 = Post.create!({user_id:u7.id, image:'https://s3.amazonaws.com/ragtagio-dev/animals/animals_3.jpeg'})
  p51 = Post.create!({user_id: u1.id, body:'all set up! #reception', image:'https://s3.amazonaws.com/ragtagio-dev/instagram/instagram_16.jpeg'})

  Like.create!({user_id:u3.id, post_id: p1.id})
  Like.create!({user_id:u3.id, post_id: p2.id})
  Like.create!({user_id:u3.id, post_id: p3.id})
  Like.create!({user_id:u3.id, post_id: p4.id})
  Like.create!({user_id:u3.id, post_id: p5.id})
  Like.create!({user_id:u1.id, post_id: p11.id})
  Like.create!({user_id:u1.id, post_id: p12.id})
  Like.create!({user_id:u1.id, post_id: p13.id})
  Like.create!({user_id:u1.id, post_id: p14.id})
  Like.create!({user_id:u1.id, post_id: p15.id})
  Like.create!({user_id:u1.id, post_id: p16.id})
  Like.create!({user_id:u1.id, post_id: p17.id})
  Like.create!({user_id:u1.id, post_id: p18.id})
  Like.create!({user_id:u1.id, post_id: p19.id})
  Like.create!({user_id:u1.id, post_id: p20.id})
  Like.create!({user_id:u1.id, post_id: p21.id})
  Like.create!({user_id:u1.id, post_id: p22.id})
  Like.create!({user_id:u2.id, post_id: p1.id})
  Like.create!({user_id:u2.id, post_id: p2.id})
  Like.create!({user_id:u2.id, post_id: p3.id})
  Like.create!({user_id:u2.id, post_id: p4.id})
  Like.create!({user_id:u2.id, post_id: p5.id})
  Like.create!({user_id:u2.id, post_id: p6.id})
  Like.create!({user_id:u2.id, post_id: p7.id})
  Like.create!({user_id:u2.id, post_id: p8.id})
  Like.create!({user_id:u2.id, post_id: p9.id})
  Like.create!({user_id:u2.id, post_id: p10.id})
  Like.create!({user_id:u2.id, post_id: p19.id})
  Like.create!({user_id:u2.id, post_id: p20.id})
  Like.create!({user_id:u2.id, post_id: p21.id})
  Like.create!({user_id:u2.id, post_id: p22.id})
  Like.create!({user_id:u2.id, post_id: p23.id})
  Like.create!({user_id:u2.id, post_id: p24.id})
  Like.create!({user_id:u4.id, post_id: p1.id})
  Like.create!({user_id:u4.id, post_id: p2.id})
  Like.create!({user_id:u4.id, post_id: p3.id})
  Like.create!({user_id:u4.id, post_id: p4.id})
  Like.create!({user_id:u4.id, post_id: p5.id})
  Like.create!({user_id:u4.id, post_id: p6.id})
  Like.create!({user_id:u4.id, post_id: p7.id})
  Like.create!({user_id:u4.id, post_id: p8.id})
  Like.create!({user_id:u4.id, post_id: p9.id})
  Like.create!({user_id:u4.id, post_id: p10.id})
  Like.create!({user_id:u4.id, post_id: p11.id})
  Like.create!({user_id:u4.id, post_id: p12.id})
  Like.create!({user_id:u4.id, post_id: p13.id})
  Like.create!({user_id:u4.id, post_id: p14.id})
  Like.create!({user_id:u4.id, post_id: p15.id})
  Like.create!({user_id:u5.id, post_id: p1.id})
  Like.create!({user_id:u5.id, post_id: p2.id})
  Like.create!({user_id:u5.id, post_id: p3.id})
  Like.create!({user_id:u5.id, post_id: p4.id})
  Like.create!({user_id:u5.id, post_id: p5.id})
  Like.create!({user_id:u5.id, post_id: p6.id})
  Like.create!({user_id:u5.id, post_id: p7.id})
  Like.create!({user_id:u5.id, post_id: p8.id})
  Like.create!({user_id:u5.id, post_id: p9.id})
  Like.create!({user_id:u5.id, post_id: p10.id})

  Comment.create!({user_id:u3.id, post_id: p1.id, body:'super!!'})
  Comment.create!({user_id:u3.id, post_id: p2.id, body:'nice!!'})
  Comment.create!({user_id:u3.id, post_id: p3.id, body:"that's so dope"})
  Comment.create!({user_id:u3.id, post_id: p4.id, body:"can't believe how nice this is!"})
  Comment.create!({user_id:u3.id, post_id: p5.id, body:"really neat! so impressed"})
  Comment.create!({user_id:u1.id, post_id: p11.id, body:"dang, this is great!"})
  Comment.create!({user_id:u1.id, post_id: p12.id, body:"wow so beautiful!"})
  Comment.create!({user_id:u1.id, post_id: p13.id, body:"this is amazing!! happy for you"})
  Comment.create!({user_id:u1.id, post_id: p14.id, body:"so proud of you and your work!!"})
  Comment.create!({user_id:u1.id, post_id: p15.id, body:"this is awesome, man"})
  Comment.create!({user_id:u1.id, post_id: p16.id, body:"dope! keep it up"})
  Comment.create!({user_id:u1.id, post_id: p17.id, body:"so cool, man!"})
  Comment.create!({user_id:u1.id, post_id: p18.id, body:"love it!"})
  Comment.create!({user_id:u1.id, post_id: p19.id, body:"i love this!!"})
  Comment.create!({user_id:u1.id, post_id: p20.id, body:"absolutely spectacular"})
  Comment.create!({user_id:u1.id, post_id: p21.id, body:"best work i've seen in a while"})
  Comment.create!({user_id:u1.id, post_id: p22.id, body:"two thumbs up my friend"})
  Comment.create!({user_id:u2.id, post_id: p1.id, body:"looking fantastic!!"})
  Comment.create!({user_id:u2.id, post_id: p2.id, body:"can't get over how great this looks!"})
  Comment.create!({user_id:u2.id, post_id: p3.id, body:"this is super impressive!"})
  Comment.create!({user_id:u2.id, post_id: p4.id, body:"really, really cool. damn!"})
  Comment.create!({user_id:u2.id, post_id: p5.id, body:"damn awesome, dude"})
  Comment.create!({user_id:u2.id, post_id: p6.id, body:"this is amazing. thank you for this!"})
  Comment.create!({user_id:u2.id, post_id: p7.id, body:"awesome! so glad you finally uploaded this :)"})
  Comment.create!({user_id:u2.id, post_id: p8.id, body:"looking fly! i love it"})
  Comment.create!({user_id:u2.id, post_id: p9.id, body:"wow i really dig this!!"})
  Comment.create!({user_id:u2.id, post_id: p10.id, body:"i'm a huge fan of this"})
  Comment.create!({user_id:u2.id, post_id: p19.id, body:"this is dope my dude"})
  Comment.create!({user_id:u2.id, post_id: p20.id, body:"impressive as always!!"})
  Comment.create!({user_id:u2.id, post_id: p21.id, body:"so nice! happy for you"})
  Comment.create!({user_id:u2.id, post_id: p22.id, body:"this is the bomb"})
  Comment.create!({user_id:u2.id, post_id: p23.id, body:"sensational. nice!!"})
  Comment.create!({user_id:u2.id, post_id: p24.id, body:"this is just pure brilliance"})
  Comment.create!({user_id:u4.id, post_id: p1.id, body:"no words. i'm blown away!"})
  Comment.create!({user_id:u4.id, post_id: p2.id, body:"shocked! amazing stuff"})
  Comment.create!({user_id:u4.id, post_id: p3.id, body:"this is so great!"})
  Comment.create!({user_id:u4.id, post_id: p4.id, body:"super! happy for you my man"})
  Comment.create!({user_id:u4.id, post_id: p5.id, body:"coolest thing i've seen all day!!"})



end
